services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webDB
      MYSQL_USER: son
      MYSQL_PASSWORD: 1234
    ports:
      - 3306:3306